### ISSUE TITLE
Package details Not showing

### ISSUE THREAD

**Issue by DavidKhrrr** [anish2065/Tour-Management#1]
The page shows the list of vacation package for different location with a package details button at the right corner but eventually it does not work. Could you please solve this issue...
![Snipaste_2022-07-03_17-18-51](https://user-images.githubusercontent.com/108612978/177037796-0e4ca3cc-c803-44f5-ad6c-8c4fceb32f1e.png)

**Comment by anish2065** [comment]
I solved the issue, now you can view the package details and it will show the details.
![Snipaste_2022-07-03_17-30-07](https://user-images.githubusercontent.com/108612653/177038155-a7884e58-b855-44dc-8183-505f086abb57.png)
