### ISSUE TITLE
Enquiry Form Submit Issue

### ISSUE THREAD

**Issue by anish2065** [anish2065/Tour-Management#3]
There is a problem while you fill the enquiry form. You can fill the form but you cannot submit after filling the form. Can you try to solve this?
![Snipaste_2022-07-03_18-55-04](https://user-images.githubusercontent.com/108612653/177041455-8456cc3e-76ac-4255-92fb-aa02b9807eb7.png)

**Comment by DavidKhrrr** [comment]
![form11](https://user-images.githubusercontent.com/108612978/177041812-6102b588-3f2a-43b1-b60b-db0ab60ef6b6.png)
Thanks for the issue I have found the bug and solved it. Now you can submit by filling the enquiry form.
![form](https://user-images.githubusercontent.com/108612978/177041724-9c8e7ab4-f86e-40d2-9f7b-c342162dbea7.png)
