### ISSUE TITLE
Alphabet in Mobile no. fill up box

### ISSUE THREAD

**Issue by anish2065** [anish2065/Tour-Management#4]
Here one can add and submit string text in the Mobile Number field box.

![99](https://user-images.githubusercontent.com/108612653/178226258-4606a8f5-ea70-4ca7-9fba-67d3f44b84b5.png)
![100](https://user-images.githubusercontent.com/108612653/178226267-3e68c3c2-885c-4bf7-9202-08dc2c4ba25c.png)
alphabet digits in the Number box.

**Comment by DavidKhrrr** [comment]
![9999](https://user-images.githubusercontent.com/108612978/178240924-4bf13b91-7c12-45f7-bd92-310c83fb65c6.png)
I have fixed the issue, you can submit with proper information.
